swagger: '2.0'
info:
  version: '1.0'
  title: Books API
  description: API для управления книгами и авторами
paths:
  /api/books/:
    get:
      tags: [Books]
      summary: Получить список всех книг
      description: Возвращает список всех книг в системе
      responses:
        200:
          description: Успешный запрос
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
    post:
      tags: [Books]
      summary: Создать новую книгу
      description: Добавляет новую книгу в систему
      parameters:
        - in: body
          name: body
          description: Данные книги
          required: true
          schema:
            $ref: '#/definitions/Book'
      responses:
        201:
          description: Книга успешно создана
          schema:
            $ref: '#/definitions/Book'
        400:
          description: Ошибка валидации
  /api/books/{book_id}:
    get:
      tags: [Books]
      summary: Получить книгу по ID
      description: Возвращает информацию о конкретной книге
      parameters:
        - name: book_id
          in: path
          description: ID книги
          required: true
          type: integer
      responses:
        200:
          description: Успешный запрос
          schema:
            $ref: '#/definitions/Book'
        404:
          description: Книга не найдена
    put:
      tags: [Books]
      summary: Обновить книгу (полное обновление)
      description: Полностью обновляет информацию о книге
      parameters:
        - name: book_id
          in: path
          description: ID книги
          required: true
          type: integer
        - in: body
          name: body
          description: Новые данные книги
          required: true
          schema:
            $ref: '#/definitions/Book'
      responses:
        200:
          description: Книга успешно обновлена
          schema:
            $ref: '#/definitions/Book'
        400:
          description: Ошибка валидации
        404:
          description: Книга не найдена
    patch:
      tags: [Books]
      summary: Обновить книгу (частичное обновление)
      description: Частично обновляет информацию о книге
      parameters:
        - name: book_id
          in: path
          description: ID книги
          required: true
          type: integer
        - in: body
          name: body
          description: Частичные данные книги
          required: true
          schema:
            $ref: '#/definitions/Book'
      responses:
        200:
          description: Книга успешно обновлена
          schema:
            $ref: '#/definitions/Book'
        400:
          description: Ошибка валидации
        404:
          description: Книга не найдена
    delete:
      tags: [Books]
      summary: Удалить книгу
      description: Удаляет книгу из системы
      parameters:
        - name: book_id
          in: path
          description: ID книги
          required: true
          type: integer
      responses:
        204:
          description: Книга успешно удалена
        404:
          description: Книга не найдена
definitions:
  Book:
    type: object
    properties:
      id:
        type: integer
        readOnly: true
        description: Уникальный идентификатор книги
      title:
        type: string
        description: Название книги
        required: true
      author_id:
        type: integer
        description: ID автора книги
        required: true
    required: [title, author_id]