global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flask-app:5050']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']